### ISSUE TITLE
Failed to find any matching files for weights_tracknet/model.1

### ISSUE THREAD

**Issue by shah0nawaz** [MaximeBataille/tennis_tracking#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for weights_tracknet/model.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict_video.py", line 69, in <module>
    m.load_weights(save_weights_path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 2199, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for weights_tracknet/model.1

I repository is very good and helpful, Please if you can solve this problem.

**Comment by MaximeBataille** [comment]
Hi, I put some instructions in the readme

Installation
Download yolov3 weights here https://pjreddie.com/darknet/yolo/ (YOLOV3-320, 45 FPS) and add it to Yolov3 directory. (This file is too heavy to push on github). Name this file yolov3.weights .

**Comment by vaibhawkhemka** [comment]
tensorflow/core/util/tensor_slice_reader.cc:95] Could not open WeightsTracknet/model.1: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

@MaximeBataille  Please fix this issue. Its unable to load the weights of "model.1"

**Comment by Boukhechba** [comment]
Getting the same error: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator

**Comment by shukkkur** [comment]
@vaibhawkhemka @Boukhechba It's a warning, not an error. Your program should do just fine. I had the same warning and the program wound not run, untill I changed the Runtime Type on Google Colab to **GPU**
